### ISSUE TITLE
Documentation more clear

### ISSUE THREAD

**Issue by charlbarrera** [mono0926/bloc_provider#16]
You have an amazing library!, but I am doing a transition from React to flutter, and I cannot understand completely your README
I am sure that if I practice I will understand the components but I hate that, could you provide more details about each step in your documentation?.

**Comment by charlbarrera** [comment]
for example:
<pre>
  final _countController = BehaviorSubject<int>.seeded(0);
  final _incrementController = PublishSubject<void>();

  CounterBloc() {
    _incrementController
        .scan<int>((sum, _v, _i) => sum + 1, 0)
        .pipe(_countController);
  }
</pre>
- from where are coming BehaviorSubject and PublishSubject? from bloc_provider library or they are an example of something in "my code".
- scan I understand that is like an acumulation of values something like .reduce() in js, am I right?
- pipe: what is the functionality of pipe here?
- We have only those methods?.

**Comment by mono0926** [comment]
Your question is about Stream API and rxdart. `bloc_provider` doesn't cover it.

And, `bloc_provider` was one of the good choice for BLoC pattern until early 2019, but I now recommend to use these instead.
I added about it: https://github.com/mono0926/bloc_provider/commit/5069fe77e82ac21ddb91088537313ac0bffed960

I'm welcome the Pull Request to enhance documentation, but I won't do it.
