### ISSUE TITLE
For readability can you add BlocProviderTree?

### ISSUE THREAD

**Issue by cosinus84** [mono0926/bloc_provider#4]
Hi,
I saw in https://pub.dartlang.org/packages/flutter_bloc BlocProviderTree witch seems a good idea when you need to use more bloc providers.
Thank you

**Comment by mono0926** [comment]
Thank you for the good advice, I’ll consider about that 👍
https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/lib/src/bloc_provider_tree.dart

**Comment by mono0926** [comment]
[BlocProviderTree](https://github.com/mono0926/bloc_provider/blob/master/lib/src/bloc_provider_tree.dart) was added, and I've released as version [0.5.0](https://pub.dartlang.org/packages/bloc_provider#050) 👍
